"""NeuroMove Synthetic EEG Signal Generator.

Produces deterministic multi-channel electrophysiological waveforms (C3, Cz, C4)
with sensorimotor rhythm (mu/beta ERD/ERS) modulation for software pipeline testing.

DISCLAIMER:
Synthetic EEG signals generated by this module are strictly for software
integration testing and algorithm scaffolding. They do NOT represent clinically
measured human electrophysiology.
"""

from __future__ import annotations

import math
import random
from datetime import UTC, datetime

from pydantic import BaseModel

from neuromove.domain.enums import Intent, OperatingMode
from neuromove.domain.models import SignalQualityMetrics
from neuromove.simulation.config import SimulationConfig


class EEGChunk(BaseModel):
    """Packetized batch of multi-channel EEG samples."""

    chunk_id: str
    timestamp: str
    sequence: int
    channels: list[str]
    sample_rate_hz: int
    samples: dict[str, list[float]]  # channel_name -> list of microvolt values
    sample_count: int
    mode: OperatingMode = OperatingMode.SIMULATION
    session_id: str | None = None
    trial_id: str | None = None


class EEGWindow(BaseModel):
    """Segmented sliding window of continuous multi-channel EEG."""

    window_id: str
    session_id: str | None = None
    trial_id: str | None = None
    start_time: str
    end_time: str
    sample_count: int
    channels: list[str]
    sample_rate_hz: int
    data: dict[str, list[float]]
    mode: OperatingMode = OperatingMode.SIMULATION


class SyntheticEEGGenerator:
    """Deterministic multi-channel synthetic EEG generator with SMR modulation."""

    def __init__(self, config: SimulationConfig | None = None) -> None:
        self.config = config or SimulationConfig()
        self._rng = random.Random(self.config.seed)
        self._sample_index: int = 0
        self._current_intent: Intent = Intent.NONE
        self._noise_multiplier: float = 1.0
        self._is_disconnected: bool = False
        self._dropped_samples_count: int = 0

    def set_intent(self, intent: Intent) -> None:
        """Set the active simulated motor imagery intent state for SMR modulation."""
        self._current_intent = intent

    def set_noise_multiplier(self, multiplier: float) -> None:
        """Adjust synthetic noise level (e.g. for failure injection testing)."""
        self._noise_multiplier = max(0.0, float(multiplier))

    def set_disconnected(self, disconnected: bool) -> None:
        """Simulate hardware lead-off or connection loss."""
        self._is_disconnected = disconnected

    def generate_samples(
        self,
        count: int,
        timestamp: datetime | None = None,
        session_id: str | None = None,
        trial_id: str | None = None,
    ) -> EEGChunk:
        """Generate `count` deterministic multi-channel EEG samples."""
        t_base = timestamp or datetime.now(UTC)
        dt = 1.0 / self.config.sample_rate_hz
        channel_data: dict[str, list[float]] = {ch: [] for ch in self.config.channels}

        for _ in range(count):
            if self._is_disconnected:
                self._dropped_samples_count += 1
                for ch in self.config.channels:
                    channel_data[ch].append(0.0)
                self._sample_index += 1
                continue

            t = self._sample_index * dt

            # 1. Slow baseline drift (0.1 - 0.5 Hz)
            drift = 5.0 * math.sin(2 * math.pi * self.config.drift_frequency_hz * t)

            # 2. Base alpha / mu (8-12 Hz) and beta (16-24 Hz) rhythms
            mu_amp_c3 = self.config.baseline_amplitude_uv
            mu_amp_c4 = self.config.baseline_amplitude_uv
            mu_amp_cz = self.config.baseline_amplitude_uv * 0.7

            # SMR (ERD / ERS) modulation based on active cognitive imagery
            # LEFT imagery: Contralateral C4 mu desynchronization (amplitude drops)
            # RIGHT imagery: Contralateral C3 mu desynchronization (amplitude drops)
            # FORWARD imagery: Bilateral desynchronization
            if self._current_intent == Intent.LEFT:
                mu_amp_c4 *= 0.3  # C4 desynchronization
                mu_amp_c3 *= 1.2  # C3 slight synchronization
            elif self._current_intent == Intent.RIGHT:
                mu_amp_c3 *= 0.3  # C3 desynchronization
                mu_amp_c4 *= 1.2  # C4 slight synchronization
            elif self._current_intent == Intent.FORWARD:
                mu_amp_c3 *= 0.4
                mu_amp_c4 *= 0.4
                mu_amp_cz *= 0.3

            # Channel specific synthesis
            for ch in self.config.channels:
                if ch == "C3":
                    mu_val = mu_amp_c3 * math.sin(2 * math.pi * self.config.mu_frequency_hz * t)
                    beta_val = (mu_amp_c3 * 0.4) * math.sin(
                        2 * math.pi * self.config.beta_frequency_hz * t
                    )
                elif ch == "C4":
                    mu_val = mu_amp_c4 * math.sin(
                        2 * math.pi * self.config.mu_frequency_hz * t + math.pi / 4
                    )
                    beta_val = (mu_amp_c4 * 0.4) * math.sin(
                        2 * math.pi * self.config.beta_frequency_hz * t + math.pi / 3
                    )
                else:  # Cz
                    mu_val = mu_amp_cz * math.sin(
                        2 * math.pi * self.config.mu_frequency_hz * t + math.pi / 2
                    )
                    beta_val = (mu_amp_cz * 0.3) * math.sin(
                        2 * math.pi * self.config.beta_frequency_hz * t
                    )

                # High frequency gamma / harmonic component (40 Hz)
                gamma_val = 2.0 * math.sin(2 * math.pi * 40.0 * t)

                # Additive Gaussian noise
                noise = self._rng.gauss(0, self.config.noise_level_uv * self._noise_multiplier)

                # Total synthesized potential in microvolts (uV)
                sample_val = round(drift + mu_val + beta_val + gamma_val + noise, 3)
                channel_data[ch].append(sample_val)

            self._sample_index += 1

        chunk_id = f"chk_{self._sample_index // count:06d}"
        return EEGChunk(
            chunk_id=chunk_id,
            timestamp=t_base.isoformat(),
            sequence=self._sample_index // count,
            channels=self.config.channels,
            sample_rate_hz=self.config.sample_rate_hz,
            samples=channel_data,
            sample_count=count,
            mode=OperatingMode.SIMULATION,
            session_id=session_id,
            trial_id=trial_id,
        )

    def compute_signal_quality(self) -> SignalQualityMetrics:
        """Compute synthetic signal quality and impedance indicators."""
        if self._is_disconnected:
            return SignalQualityMetrics(
                overall_score=0.0,
                channels=dict.fromkeys(self.config.channels, 0.0),
                dropped_samples=self._dropped_samples_count,
                artifact_flags=["LEAD_OFF", "DISCONNECTED"],
                sampling_rate_hz=self.config.sample_rate_hz,
                is_acceptable=False,
            )

        # Quality decreases as noise multiplier increases
        base_score = max(0.05, min(1.0, 1.0 - (self._noise_multiplier - 1.0) * 0.25))
        channel_scores = {
            ch: round(base_score * self._rng.uniform(0.92, 1.0), 3) for ch in self.config.channels
        }
        overall = round(sum(channel_scores.values()) / len(channel_scores), 3)
        flags: list[str] = []
        if self._noise_multiplier > 2.0:
            flags.append("HIGH_NOISE")
        if self.config.enable_artifacts and self._rng.random() < 0.05:
            flags.append("OCULAR_BLINK")

        return SignalQualityMetrics(
            overall_score=overall,
            channels=channel_scores,
            dropped_samples=self._dropped_samples_count,
            artifact_flags=flags,
            sampling_rate_hz=self.config.sample_rate_hz,
            is_acceptable=overall >= 0.70,
        )
