"""NeuroMove Canonical Domain Enumerations.

Defines the single source of truth for runtime modes, intents, states,
safety categories, command statuses, and the universal event taxonomy.
"""

from enum import StrEnum


class OperatingMode(StrEnum):
    """Runtime operational mode for data and control routing."""

    LIVE = "LIVE"
    REPLAY = "REPLAY"
    SIMULATION = "SIMULATION"


class Intent(StrEnum):
    """Decoded or candidate motor-imagery neural intents."""

    NONE = "NONE"
    LEFT = "LEFT"
    RIGHT = "RIGHT"
    FORWARD = "FORWARD"
    BACKWARD = "BACKWARD"
    STOP = "STOP"
    UNCERTAIN = "UNCERTAIN"


class RuntimeState(StrEnum):
    """Deterministic system runtime and safety lifecycle states."""

    IDLE = "IDLE"
    CALIBRATING = "CALIBRATING"
    READY = "READY"
    CANDIDATE = "CANDIDATE"
    CONFIRMED = "CONFIRMED"
    EXECUTING = "EXECUTING"
    BLOCKED = "BLOCKED"
    EMERGENCY = "EMERGENCY"
    FAULT = "FAULT"
    UNCERTAIN = "UNCERTAIN"


class SafetyDecision(StrEnum):
    """Safety arbitration verdicts."""

    # Phase 17 Canonical Decisions
    AUTHORIZED = "AUTHORIZED"
    HELD = "HELD"
    DENIED = "DENIED"
    EMERGENCY_STOP = "EMERGENCY_STOP"
    LOCKED_OUT = "LOCKED_OUT"
    INVALID = "INVALID"

    # Legacy Aliases
    APPROVED = "APPROVED"
    BLOCKED = "BLOCKED"
    STOP = "STOP"


class RiskLevel(StrEnum):
    """Environmental and intent risk classifications."""

    SAFE = "SAFE"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class ConnectionState(StrEnum):
    """Hardware and network subsystem connection statuses."""

    CONNECTED = "CONNECTED"
    DEGRADED = "DEGRADED"
    DISCONNECTED = "DISCONNECTED"


class CommandStatus(StrEnum):
    """Mobility command dispatch lifecycle states."""

    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    BLOCKED = "BLOCKED"
    SENT = "SENT"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class SessionStatus(StrEnum):
    """Research and trial recording session states."""

    CREATED = "CREATED"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    ABORTED = "ABORTED"


class TrialQuality(StrEnum):
    """Electrophysiological trial data quality validation flag."""

    VALID = "VALID"
    DEGRADED = "DEGRADED"
    REJECTED = "REJECTED"


class ComponentStatus(StrEnum):
    """Granular health status of individual subsystems."""

    HEALTHY = "healthy"
    READY = "ready"
    DEGRADED = "degraded"
    NOT_CONNECTED = "not_connected"
    NOT_INITIALIZED = "not_initialized"
    UNAVAILABLE = "unavailable"
    ERROR = "error"


class EventType(StrEnum):
    """Universal classification of canonical envelope event payloads."""

    # System Lifecycle & Health
    SYSTEM_STARTED = "SYSTEM_STARTED"
    SYSTEM_STOPPED = "SYSTEM_STOPPED"
    SYSTEM_STATUS = "SYSTEM_STATUS"

    # Session Lifecycle
    SESSION_CREATED = "SESSION_CREATED"
    SESSION_STARTED = "SESSION_STARTED"
    SESSION_PAUSED = "SESSION_PAUSED"
    SESSION_RESUMED = "SESSION_RESUMED"
    SESSION_ENDED = "SESSION_ENDED"

    # Trial Protocol
    TRIAL_STARTED = "TRIAL_STARTED"
    TRIAL_CUE = "TRIAL_CUE"
    TRIAL_IMAGERY_STARTED = "TRIAL_IMAGERY_STARTED"
    TRIAL_ENDED = "TRIAL_ENDED"

    # EEG Stream & Signal Quality
    EEG_PACKET = "EEG_PACKET"
    EEG_WINDOW = "EEG_WINDOW"
    EEG_SIGNAL_QUALITY = "EEG_SIGNAL_QUALITY"
    EEG_DISCONNECTED = "EEG_DISCONNECTED"
    TELEMETRY = "TELEMETRY"

    # BCI Prediction & Intent Lifecycle (Phase 16)
    PREDICTION = "PREDICTION"
    INTENT_CANDIDATE = "INTENT_CANDIDATE"
    INTENT_CONFIRMED = "INTENT_CONFIRMED"
    INTENT_ACTIVATED = "INTENT_ACTIVATED"
    INTENT_CANCELLED = "INTENT_CANCELLED"
    INTENT_EXPIRED = "INTENT_EXPIRED"
    INTENT_INTERRUPTED = "INTENT_INTERRUPTED"
    INTENT_COMPLETED = "INTENT_COMPLETED"
    INTENT_REPLACEMENT_REQUESTED = "INTENT_REPLACEMENT_REQUESTED"
    INTENT_STATE_CHANGED = "INTENT_STATE_CHANGED"
    INTENT_CONTEXT_RESET = "INTENT_CONTEXT_RESET"
    INTENT_REJECTED = "INTENT_REJECTED"

    # Confidence & Temporal Confirmation (Phase 15)
    CONFIDENCE_EVALUATED = "CONFIDENCE_EVALUATED"
    CONFIDENCE_REJECTED = "CONFIDENCE_REJECTED"
    TEMPORAL_EVIDENCE_UPDATED = "TEMPORAL_EVIDENCE_UPDATED"
    TEMPORAL_CONFIRMATION_REACHED = "TEMPORAL_CONFIRMATION_REACHED"
    TEMPORAL_CONFIRMATION_RESET = "TEMPORAL_CONFIRMATION_RESET"
    CONFIDENCE_STATE_EXPIRED = "CONFIDENCE_STATE_EXPIRED"
    CONFIDENCE_CONFIG_CHANGED = "CONFIDENCE_CONFIG_CHANGED"

    # Safety State Machine & Arbitration (Phase 17)
    SAFETY_EVALUATED = "SAFETY_EVALUATED"
    SAFETY_AUTHORIZED = "SAFETY_AUTHORIZED"
    SAFETY_HELD = "SAFETY_HELD"
    SAFETY_DENIED = "SAFETY_DENIED"
    SAFETY_EMERGENCY_STOP = "SAFETY_EMERGENCY_STOP"
    SAFETY_LOCKED_OUT = "SAFETY_LOCKED_OUT"
    SAFETY_RESET = "SAFETY_RESET"
    SAFETY_HOLD_CHANGED = "SAFETY_HOLD_CHANGED"
    SAFETY_CONTEXT_CHANGED = "SAFETY_CONTEXT_CHANGED"
    STATE_TRANSITION = "STATE_TRANSITION"
    SAFETY_CHECK = "SAFETY_CHECK"
    SAFETY_APPROVED = "SAFETY_APPROVED"
    SAFETY_BLOCKED = "SAFETY_BLOCKED"
    SAFETY_STOP = "SAFETY_STOP"
    EMERGENCY_STOP = "EMERGENCY_STOP"
    SAFETY_ALERT = "SAFETY_ALERT"
    DECISION = "DECISION"
    FAULT = "FAULT"

    # Robot Mobility & Command Protocol
    ROBOT_STATE = "ROBOT_STATE"
    ROBOT_COMMAND_REQUESTED = "ROBOT_COMMAND_REQUESTED"
    ROBOT_COMMAND_APPROVED = "ROBOT_COMMAND_APPROVED"
    ROBOT_COMMAND_BLOCKED = "ROBOT_COMMAND_BLOCKED"
    ROBOT_COMMAND_SENT = "ROBOT_COMMAND_SENT"
    ROBOT_COMMAND_ACK = "ROBOT_COMMAND_ACK"
    ROBOT_COMMAND_FAILED = "ROBOT_COMMAND_FAILED"
    ROBOT_COMMAND = "ROBOT_COMMAND"

    # Calibration Protocols
    CALIBRATION_STARTED = "CALIBRATION_STARTED"
    CALIBRATION_TRIAL = "CALIBRATION_TRIAL"
    CALIBRATION_COMPLETED = "CALIBRATION_COMPLETED"
    CALIBRATION_FAILED = "CALIBRATION_FAILED"
    CALIBRATION = "CALIBRATION"

    # Experiment Management
    EXPERIMENT_CREATED = "EXPERIMENT_CREATED"
    EXPERIMENT_STARTED = "EXPERIMENT_STARTED"
    EXPERIMENT_COMPLETED = "EXPERIMENT_COMPLETED"

    # Fault Laboratory & Resilience (Phase 18)
    FAULT_DECLARED = "FAULT_DECLARED"
    FAULT_ACTIVE = "FAULT_ACTIVE"
    FAULT_DETECTED = "FAULT_DETECTED"
    FAULT_CLEARED = "FAULT_CLEARED"
    RECOVERY_STARTED = "RECOVERY_STARTED"
    RECOVERY_COMPLETED = "RECOVERY_COMPLETED"
    RECOVERY_FAILED = "RECOVERY_FAILED"
    INVARIANT_PASSED = "INVARIANT_PASSED"
    INVARIANT_FAILED = "INVARIANT_FAILED"
    RESILIENCE_EXPERIMENT_STARTED = "RESILIENCE_EXPERIMENT_STARTED"
    RESILIENCE_EXPERIMENT_COMPLETED = "RESILIENCE_EXPERIMENT_COMPLETED"

    # Command Transport & ESP32 Protocol (Phase 19)
    TRANSPORT_CONNECTED = "TRANSPORT_CONNECTED"
    TRANSPORT_DISCONNECTED = "TRANSPORT_DISCONNECTED"
    TRANSPORT_NEGOTIATING = "TRANSPORT_NEGOTIATING"
    TRANSPORT_NEGOTIATED = "TRANSPORT_NEGOTIATED"
    TRANSPORT_DEGRADED = "TRANSPORT_DEGRADED"
    TRANSPORT_COMMAND_CREATED = "TRANSPORT_COMMAND_CREATED"
    TRANSPORT_COMMAND_SENT = "TRANSPORT_COMMAND_SENT"
    TRANSPORT_COMMAND_ACKED = "TRANSPORT_COMMAND_ACKED"
    TRANSPORT_COMMAND_REJECTED = "TRANSPORT_COMMAND_REJECTED"
    TRANSPORT_COMMAND_RETRIED = "TRANSPORT_COMMAND_RETRIED"
    TRANSPORT_COMMAND_EXPIRED = "TRANSPORT_COMMAND_EXPIRED"
    TRANSPORT_SEQUENCE_GAP = "TRANSPORT_SEQUENCE_GAP"
    TRANSPORT_CHECKSUM_FAILURE = "TRANSPORT_CHECKSUM_FAILURE"
    TRANSPORT_HEARTBEAT = "TRANSPORT_HEARTBEAT"

    # Hardware-in-the-Loop & ESP32 Adapter (Phase 20)
    HARDWARE_DISCOVERED = "HARDWARE_DISCOVERED"
    HARDWARE_CONNECTING = "HARDWARE_CONNECTING"
    HARDWARE_CONNECTED = "HARDWARE_CONNECTED"
    HARDWARE_NEGOTIATING = "HARDWARE_NEGOTIATING"
    HARDWARE_NEGOTIATED = "HARDWARE_NEGOTIATED"
    HARDWARE_READY = "HARDWARE_READY"
    HARDWARE_DEGRADED = "HARDWARE_DEGRADED"
    HARDWARE_STALE = "HARDWARE_STALE"
    HARDWARE_DISCONNECTED = "HARDWARE_DISCONNECTED"
    HARDWARE_RECONNECTING = "HARDWARE_RECONNECTING"
    HARDWARE_REBOOTED = "HARDWARE_REBOOTED"
    HARDWARE_CAPABILITIES_UPDATED = "HARDWARE_CAPABILITIES_UPDATED"
    HARDWARE_COMMAND_STATUS = "HARDWARE_COMMAND_STATUS"
    HARDWARE_DIAGNOSTIC = "HARDWARE_DIAGNOSTIC"
    HARDWARE_ERROR = "HARDWARE_ERROR"

    # Real EEG / BioAmp Acquisition (Phase 21)
    EEG_ACQUISITION_DISCOVERED = "EEG_ACQUISITION_DISCOVERED"
    EEG_ACQUISITION_CONNECTING = "EEG_ACQUISITION_CONNECTING"
    EEG_ACQUISITION_CONNECTED = "EEG_ACQUISITION_CONNECTED"
    EEG_ACQUISITION_CONFIGURED = "EEG_ACQUISITION_CONFIGURED"
    EEG_ACQUISITION_CALIBRATING = "EEG_ACQUISITION_CALIBRATING"
    EEG_ACQUISITION_CALIBRATED = "EEG_ACQUISITION_CALIBRATED"
    EEG_ACQUISITION_STREAMING = "EEG_ACQUISITION_STREAMING"
    EEG_ACQUISITION_PAUSED = "EEG_ACQUISITION_PAUSED"
    EEG_ACQUISITION_DEGRADED = "EEG_ACQUISITION_DEGRADED"
    EEG_ACQUISITION_STALE = "EEG_ACQUISITION_STALE"
    EEG_ACQUISITION_DISCONNECTED = "EEG_ACQUISITION_DISCONNECTED"
    EEG_ACQUISITION_RECONNECTING = "EEG_ACQUISITION_RECONNECTING"
    EEG_ACQUISITION_DIAGNOSTIC = "EEG_ACQUISITION_DIAGNOSTIC"
    EEG_ACQUISITION_HEALTH = "EEG_ACQUISITION_HEALTH"
    EEG_ACQUISITION_RECORDING_STARTED = "EEG_ACQUISITION_RECORDING_STARTED"
    EEG_ACQUISITION_RECORDING_STOPPED = "EEG_ACQUISITION_RECORDING_STOPPED"
    EEG_ACQUISITION_REPLAY_STARTED = "EEG_ACQUISITION_REPLAY_STARTED"
    EEG_ACQUISITION_REPLAY_STOPPED = "EEG_ACQUISITION_REPLAY_STOPPED"
    EEG_ACQUISITION_ERROR = "EEG_ACQUISITION_ERROR"
