"""NeuroMove Canonical Domain Enumerations.

Defines the single source of truth for runtime modes, intents, states,
safety categories, command statuses, and the universal event taxonomy.
"""

from enum import StrEnum


class OperatingMode(StrEnum):
    """Runtime operational mode for data and control routing."""

    LIVE = "LIVE"
    REPLAY = "REPLAY"
    SIMULATION = "SIMULATION"


class Intent(StrEnum):
    """Decoded or candidate motor-imagery neural intents."""

    NONE = "NONE"
    LEFT = "LEFT"
    RIGHT = "RIGHT"
    FORWARD = "FORWARD"
    BACKWARD = "BACKWARD"
    STOP = "STOP"
    UNCERTAIN = "UNCERTAIN"


class RuntimeState(StrEnum):
    """Deterministic system runtime and safety lifecycle states."""

    IDLE = "IDLE"
    CALIBRATING = "CALIBRATING"
    READY = "READY"
    CANDIDATE = "CANDIDATE"
    CONFIRMED = "CONFIRMED"
    EXECUTING = "EXECUTING"
    BLOCKED = "BLOCKED"
    EMERGENCY = "EMERGENCY"
    FAULT = "FAULT"
    UNCERTAIN = "UNCERTAIN"


class SafetyDecision(StrEnum):
    """Safety arbitration verdicts."""

    # Phase 17 Canonical Decisions
    AUTHORIZED = "AUTHORIZED"
    HELD = "HELD"
    DENIED = "DENIED"
    EMERGENCY_STOP = "EMERGENCY_STOP"
    LOCKED_OUT = "LOCKED_OUT"
    INVALID = "INVALID"

    # Legacy Aliases
    APPROVED = "APPROVED"
    BLOCKED = "BLOCKED"
    STOP = "STOP"


class RiskLevel(StrEnum):
    """Environmental and intent risk classifications."""

    SAFE = "SAFE"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class ConnectionState(StrEnum):
    """Hardware and network subsystem connection statuses."""

    CONNECTED = "CONNECTED"
    DEGRADED = "DEGRADED"
    DISCONNECTED = "DISCONNECTED"


class CommandStatus(StrEnum):
    """Mobility command dispatch lifecycle states."""

    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    BLOCKED = "BLOCKED"
    SENT = "SENT"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class SessionStatus(StrEnum):
    """Research and trial recording session states."""

    CREATED = "CREATED"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    ABORTED = "ABORTED"


class TrialQuality(StrEnum):
    """Electrophysiological trial data quality validation flag."""

    VALID = "VALID"
    DEGRADED = "DEGRADED"
    REJECTED = "REJECTED"


class ComponentStatus(StrEnum):
    """Granular health status of individual subsystems."""

    HEALTHY = "healthy"
    READY = "ready"
    DEGRADED = "degraded"
    NOT_CONNECTED = "not_connected"
    NOT_INITIALIZED = "not_initialized"
    UNAVAILABLE = "unavailable"
    ERROR = "error"


class EventType(StrEnum):
    """Universal classification of canonical envelope event payloads."""

    # System Lifecycle & Health
    SYSTEM_STARTED = "SYSTEM_STARTED"
    SYSTEM_STOPPED = "SYSTEM_STOPPED"
    SYSTEM_STATUS = "SYSTEM_STATUS"

    # Session Lifecycle
    SESSION_CREATED = "SESSION_CREATED"
    SESSION_STARTED = "SESSION_STARTED"
    SESSION_PAUSED = "SESSION_PAUSED"
    SESSION_RESUMED = "SESSION_RESUMED"
    SESSION_ENDED = "SESSION_ENDED"

    # Trial Protocol
    TRIAL_STARTED = "TRIAL_STARTED"
    TRIAL_CUE = "TRIAL_CUE"
    TRIAL_IMAGERY_STARTED = "TRIAL_IMAGERY_STARTED"
    TRIAL_ENDED = "TRIAL_ENDED"

    # EEG Stream & Signal Quality
    EEG_PACKET = "EEG_PACKET"
    EEG_WINDOW = "EEG_WINDOW"
    EEG_SIGNAL_QUALITY = "EEG_SIGNAL_QUALITY"
    EEG_DISCONNECTED = "EEG_DISCONNECTED"
    TELEMETRY = "TELEMETRY"

    # BCI Prediction & Intent Lifecycle (Phase 16)
    PREDICTION = "PREDICTION"
    INTENT_CANDIDATE = "INTENT_CANDIDATE"
    INTENT_CONFIRMED = "INTENT_CONFIRMED"
    INTENT_ACTIVATED = "INTENT_ACTIVATED"
    INTENT_CANCELLED = "INTENT_CANCELLED"
    INTENT_EXPIRED = "INTENT_EXPIRED"
    INTENT_INTERRUPTED = "INTENT_INTERRUPTED"
    INTENT_COMPLETED = "INTENT_COMPLETED"
    INTENT_REPLACEMENT_REQUESTED = "INTENT_REPLACEMENT_REQUESTED"
    INTENT_STATE_CHANGED = "INTENT_STATE_CHANGED"
    INTENT_CONTEXT_RESET = "INTENT_CONTEXT_RESET"
    INTENT_REJECTED = "INTENT_REJECTED"

    # Confidence & Temporal Confirmation (Phase 15)
    CONFIDENCE_EVALUATED = "CONFIDENCE_EVALUATED"
    CONFIDENCE_REJECTED = "CONFIDENCE_REJECTED"
    TEMPORAL_EVIDENCE_UPDATED = "TEMPORAL_EVIDENCE_UPDATED"
    TEMPORAL_CONFIRMATION_REACHED = "TEMPORAL_CONFIRMATION_REACHED"
    TEMPORAL_CONFIRMATION_RESET = "TEMPORAL_CONFIRMATION_RESET"
    CONFIDENCE_STATE_EXPIRED = "CONFIDENCE_STATE_EXPIRED"
    CONFIDENCE_CONFIG_CHANGED = "CONFIDENCE_CONFIG_CHANGED"

    # Safety State Machine & Arbitration (Phase 17)
    SAFETY_EVALUATED = "SAFETY_EVALUATED"
    SAFETY_AUTHORIZED = "SAFETY_AUTHORIZED"
    SAFETY_HELD = "SAFETY_HELD"
    SAFETY_DENIED = "SAFETY_DENIED"
    SAFETY_EMERGENCY_STOP = "SAFETY_EMERGENCY_STOP"
    SAFETY_LOCKED_OUT = "SAFETY_LOCKED_OUT"
    SAFETY_RESET = "SAFETY_RESET"
    SAFETY_HOLD_CHANGED = "SAFETY_HOLD_CHANGED"
    SAFETY_CONTEXT_CHANGED = "SAFETY_CONTEXT_CHANGED"
    STATE_TRANSITION = "STATE_TRANSITION"
    SAFETY_CHECK = "SAFETY_CHECK"
    SAFETY_APPROVED = "SAFETY_APPROVED"
    SAFETY_BLOCKED = "SAFETY_BLOCKED"
    SAFETY_STOP = "SAFETY_STOP"
    EMERGENCY_STOP = "EMERGENCY_STOP"
    SAFETY_ALERT = "SAFETY_ALERT"
    DECISION = "DECISION"
    FAULT = "FAULT"

    # Robot Mobility & Command Protocol
    ROBOT_STATE = "ROBOT_STATE"
    ROBOT_COMMAND_REQUESTED = "ROBOT_COMMAND_REQUESTED"
    ROBOT_COMMAND_APPROVED = "ROBOT_COMMAND_APPROVED"
    ROBOT_COMMAND_BLOCKED = "ROBOT_COMMAND_BLOCKED"
    ROBOT_COMMAND_SENT = "ROBOT_COMMAND_SENT"
    ROBOT_COMMAND_ACK = "ROBOT_COMMAND_ACK"
    ROBOT_COMMAND_FAILED = "ROBOT_COMMAND_FAILED"
    ROBOT_COMMAND = "ROBOT_COMMAND"

    # Calibration Protocols
    CALIBRATION_STARTED = "CALIBRATION_STARTED"
    CALIBRATION_TRIAL = "CALIBRATION_TRIAL"
    CALIBRATION_COMPLETED = "CALIBRATION_COMPLETED"
    CALIBRATION_FAILED = "CALIBRATION_FAILED"
    CALIBRATION = "CALIBRATION"

    # Experiment Management
    EXPERIMENT_CREATED = "EXPERIMENT_CREATED"
    EXPERIMENT_STARTED = "EXPERIMENT_STARTED"
    EXPERIMENT_COMPLETED = "EXPERIMENT_COMPLETED"

    # Fault Laboratory & Resilience (Phase 18)
    FAULT_DECLARED = "FAULT_DECLARED"
    FAULT_ACTIVE = "FAULT_ACTIVE"
    FAULT_DETECTED = "FAULT_DETECTED"
    FAULT_CLEARED = "FAULT_CLEARED"
    RECOVERY_STARTED = "RECOVERY_STARTED"
    RECOVERY_COMPLETED = "RECOVERY_COMPLETED"
    RECOVERY_FAILED = "RECOVERY_FAILED"
    INVARIANT_PASSED = "INVARIANT_PASSED"
    INVARIANT_FAILED = "INVARIANT_FAILED"
    RESILIENCE_EXPERIMENT_STARTED = "RESILIENCE_EXPERIMENT_STARTED"
    RESILIENCE_EXPERIMENT_COMPLETED = "RESILIENCE_EXPERIMENT_COMPLETED"

    # Command Transport & ESP32 Protocol (Phase 19)
    TRANSPORT_CONNECTED = "TRANSPORT_CONNECTED"
    TRANSPORT_DISCONNECTED = "TRANSPORT_DISCONNECTED"
    TRANSPORT_NEGOTIATING = "TRANSPORT_NEGOTIATING"
    TRANSPORT_NEGOTIATED = "TRANSPORT_NEGOTIATED"
    TRANSPORT_DEGRADED = "TRANSPORT_DEGRADED"
    TRANSPORT_COMMAND_CREATED = "TRANSPORT_COMMAND_CREATED"
    TRANSPORT_COMMAND_SENT = "TRANSPORT_COMMAND_SENT"
    TRANSPORT_COMMAND_ACKED = "TRANSPORT_COMMAND_ACKED"
    TRANSPORT_COMMAND_REJECTED = "TRANSPORT_COMMAND_REJECTED"
    TRANSPORT_COMMAND_RETRIED = "TRANSPORT_COMMAND_RETRIED"
    TRANSPORT_COMMAND_EXPIRED = "TRANSPORT_COMMAND_EXPIRED"
    TRANSPORT_SEQUENCE_GAP = "TRANSPORT_SEQUENCE_GAP"
    TRANSPORT_CHECKSUM_FAILURE = "TRANSPORT_CHECKSUM_FAILURE"
    TRANSPORT_HEARTBEAT = "TRANSPORT_HEARTBEAT"

    # Hardware-in-the-Loop & ESP32 Adapter (Phase 20)
    HARDWARE_DISCOVERED = "HARDWARE_DISCOVERED"
    HARDWARE_CONNECTING = "HARDWARE_CONNECTING"
    HARDWARE_CONNECTED = "HARDWARE_CONNECTED"
    HARDWARE_NEGOTIATING = "HARDWARE_NEGOTIATING"
    HARDWARE_NEGOTIATED = "HARDWARE_NEGOTIATED"
    HARDWARE_READY = "HARDWARE_READY"
    HARDWARE_DEGRADED = "HARDWARE_DEGRADED"
    HARDWARE_STALE = "HARDWARE_STALE"
    HARDWARE_DISCONNECTED = "HARDWARE_DISCONNECTED"
    HARDWARE_RECONNECTING = "HARDWARE_RECONNECTING"
    HARDWARE_REBOOTED = "HARDWARE_REBOOTED"
    HARDWARE_CAPABILITIES_UPDATED = "HARDWARE_CAPABILITIES_UPDATED"
    HARDWARE_COMMAND_STATUS = "HARDWARE_COMMAND_STATUS"
    HARDWARE_DIAGNOSTIC = "HARDWARE_DIAGNOSTIC"
    HARDWARE_ERROR = "HARDWARE_ERROR"

    # Real EEG / BioAmp Acquisition (Phase 21)
    EEG_ACQUISITION_DISCOVERED = "EEG_ACQUISITION_DISCOVERED"
    EEG_ACQUISITION_CONNECTING = "EEG_ACQUISITION_CONNECTING"
    EEG_ACQUISITION_CONNECTED = "EEG_ACQUISITION_CONNECTED"
    EEG_ACQUISITION_CONFIGURED = "EEG_ACQUISITION_CONFIGURED"
    EEG_ACQUISITION_CALIBRATING = "EEG_ACQUISITION_CALIBRATING"
    EEG_ACQUISITION_CALIBRATED = "EEG_ACQUISITION_CALIBRATED"
    EEG_ACQUISITION_STREAMING = "EEG_ACQUISITION_STREAMING"
    EEG_ACQUISITION_PAUSED = "EEG_ACQUISITION_PAUSED"
    EEG_ACQUISITION_DEGRADED = "EEG_ACQUISITION_DEGRADED"
    EEG_ACQUISITION_STALE = "EEG_ACQUISITION_STALE"
    EEG_ACQUISITION_DISCONNECTED = "EEG_ACQUISITION_DISCONNECTED"
    EEG_ACQUISITION_RECONNECTING = "EEG_ACQUISITION_RECONNECTING"
    EEG_ACQUISITION_DIAGNOSTIC = "EEG_ACQUISITION_DIAGNOSTIC"
    EEG_ACQUISITION_HEALTH = "EEG_ACQUISITION_HEALTH"
    EEG_ACQUISITION_RECORDING_STARTED = "EEG_ACQUISITION_RECORDING_STARTED"
    EEG_ACQUISITION_RECORDING_STOPPED = "EEG_ACQUISITION_RECORDING_STOPPED"
    EEG_ACQUISITION_REPLAY_STARTED = "EEG_ACQUISITION_REPLAY_STARTED"
    EEG_ACQUISITION_REPLAY_STOPPED = "EEG_ACQUISITION_REPLAY_STOPPED"
    EEG_ACQUISITION_ERROR = "EEG_ACQUISITION_ERROR"

    # Deterministic Replay & Scientific Evaluation (Phase 22)
    RESEARCH_EXPERIMENT_CREATED = "RESEARCH_EXPERIMENT_CREATED"
    RESEARCH_EXPERIMENT_SEALED = "RESEARCH_EXPERIMENT_SEALED"
    RESEARCH_EXPERIMENT_STARTED = "RESEARCH_EXPERIMENT_STARTED"
    RESEARCH_EXPERIMENT_PAUSED = "RESEARCH_EXPERIMENT_PAUSED"
    RESEARCH_EXPERIMENT_RESUMED = "RESEARCH_EXPERIMENT_RESUMED"
    RESEARCH_EXPERIMENT_COMPLETED = "RESEARCH_EXPERIMENT_COMPLETED"
    RESEARCH_EXPERIMENT_FAILED = "RESEARCH_EXPERIMENT_FAILED"
    RESEARCH_EXPERIMENT_CANCELLED = "RESEARCH_EXPERIMENT_CANCELLED"
    RESEARCH_REPLAY_STEP = "RESEARCH_REPLAY_STEP"
    RESEARCH_REPLAY_CHECKPOINT = "RESEARCH_REPLAY_CHECKPOINT"
    RESEARCH_STAGE_COMPLETED = "RESEARCH_STAGE_COMPLETED"
    RESEARCH_METRICS_UPDATED = "RESEARCH_METRICS_UPDATED"
    RESEARCH_ABLATION_COMPLETED = "RESEARCH_ABLATION_COMPLETED"
    RESEARCH_ROBUSTNESS_COMPLETED = "RESEARCH_ROBUSTNESS_COMPLETED"
    RESEARCH_COMPARISON_COMPLETED = "RESEARCH_COMPARISON_COMPLETED"
    RESEARCH_REPRODUCIBILITY_CHECKED = "RESEARCH_REPRODUCIBILITY_CHECKED"
    RESEARCH_ARTIFACT_EXPORTED = "RESEARCH_ARTIFACT_EXPORTED"
    RESEARCH_DIAGNOSTIC = "RESEARCH_DIAGNOSTIC"
    RESEARCH_ERROR = "RESEARCH_ERROR"

    # Multimodal Sensors & Context Engine (Phase 23)
    SENSOR_DISCOVERED = "SENSOR_DISCOVERED"
    SENSOR_CONNECTING = "SENSOR_CONNECTING"
    SENSOR_CONNECTED = "SENSOR_CONNECTED"
    SENSOR_CONFIGURED = "SENSOR_CONFIGURED"
    SENSOR_CALIBRATING = "SENSOR_CALIBRATING"
    SENSOR_CALIBRATED = "SENSOR_CALIBRATED"
    SENSOR_STREAMING = "SENSOR_STREAMING"
    SENSOR_PAUSED = "SENSOR_PAUSED"
    SENSOR_DEGRADED = "SENSOR_DEGRADED"
    SENSOR_STALE = "SENSOR_STALE"
    SENSOR_DISCONNECTED = "SENSOR_DISCONNECTED"
    SENSOR_RECONNECTING = "SENSOR_RECONNECTING"
    SENSOR_DIAGNOSTIC = "SENSOR_DIAGNOSTIC"
    SENSOR_HEALTH_UPDATED = "SENSOR_HEALTH_UPDATED"
    SENSOR_SYNC_UPDATED = "SENSOR_SYNC_UPDATED"
    SENSOR_FUSION_COMPLETED = "SENSOR_FUSION_COMPLETED"
    SENSOR_CONTEXT_UPDATED = "SENSOR_CONTEXT_UPDATED"
    SENSOR_CONTRADICTION_DETECTED = "SENSOR_CONTRADICTION_DETECTED"
    SENSOR_ERROR = "SENSOR_ERROR"

    # Final Product & Demo Orchestration (Phase 24.1)
    PRODUCT_SESSION_CREATED = "PRODUCT_SESSION_CREATED"
    PRODUCT_SESSION_READY = "PRODUCT_SESSION_READY"
    PRODUCT_SESSION_RESET = "PRODUCT_SESSION_RESET"
    PRODUCT_DEMO_STARTED = "PRODUCT_DEMO_STARTED"
    PRODUCT_DEMO_PAUSED = "PRODUCT_DEMO_PAUSED"
    PRODUCT_DEMO_RESUMED = "PRODUCT_DEMO_RESUMED"
    PRODUCT_DEMO_STEP_COMPLETED = "PRODUCT_DEMO_STEP_COMPLETED"
    PRODUCT_STAGE_CHANGED = "PRODUCT_STAGE_CHANGED"
    PRODUCT_SAFETY_BLOCKED = "PRODUCT_SAFETY_BLOCKED"
    PRODUCT_HIL_COMPLETED = "PRODUCT_HIL_COMPLETED"
    PRODUCT_DEMO_COMPLETED = "PRODUCT_DEMO_COMPLETED"
    PRODUCT_DEMO_FAILED = "PRODUCT_DEMO_FAILED"


class SensorModality(StrEnum):
    """Supported multimodal sensor signal modalities."""

    EEG = "EEG"
    IMU = "IMU"
    EMG = "EMG"
    EOG = "EOG"
    PPG = "PPG"
    PRESSURE = "PRESSURE"
    AUXILIARY = "AUXILIARY"


class SensorSource(StrEnum):
    """Source provider for multimodal sensor streams."""

    PHYSICAL = "PHYSICAL"
    SIMULATOR = "SIMULATOR"
    RECORDED = "RECORDED"


class SensorState(StrEnum):
    """Finite lifecycle state of a sensor device."""

    DISCONNECTED = "DISCONNECTED"
    DISCOVERING = "DISCOVERING"
    CONNECTING = "CONNECTING"
    CONFIGURING = "CONFIGURING"
    CALIBRATING = "CALIBRATING"
    STREAMING = "STREAMING"
    PAUSED = "PAUSED"
    DEGRADED = "DEGRADED"
    STALE = "STALE"
    RECONNECTING = "RECONNECTING"
    STOPPING = "STOPPING"
    ERROR = "ERROR"


class SynchronizationStatus(StrEnum):
    """Inter-sensor stream clock alignment state."""

    SYNCHRONIZED = "SYNCHRONIZED"
    DEGRADED = "DEGRADED"
    UNSYNCHRONIZED = "UNSYNCHRONIZED"
    DRIFT_DETECTED = "DRIFT_DETECTED"
    RESYNCING = "RESYNCING"
    FAILED = "FAILED"


class ContradictionOutcome(StrEnum):
    """Safety consequence of a multimodal contradiction."""

    INFORMATIONAL = "INFORMATIONAL"
    DEGRADED = "DEGRADED"
    HOLD = "HOLD"
    INVALID = "INVALID"


class MotionContaminationState(StrEnum):
    """Movement context classifier for EEG artifact likelihood."""

    MOTION_QUIET = "MOTION_QUIET"
    MOTION_ACTIVE = "MOTION_ACTIVE"
    LIKELY_CONTAMINATED = "LIKELY_CONTAMINATED"
    UNKNOWN = "UNKNOWN"


class FusionStrategy(StrEnum):
    """Deterministic multimodal sensor fusion algorithm."""

    TEMPORAL_COINCIDENCE = "TEMPORAL_COINCIDENCE"
    RULE_BASED_CONTEXT = "RULE_BASED_CONTEXT"
    FEATURE_LEVEL = "FEATURE_LEVEL"
    DECISION_LEVEL = "DECISION_LEVEL"
    CONFIDENCE_MODULATION = "CONFIDENCE_MODULATION"
    CONTRADICTION_GATED = "CONTRADICTION_GATED"


class ProductSessionStatus(StrEnum):
    """Lifecycle status of a unified competition product session."""

    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    HELD = "HELD"
    RESET = "RESET"
    FAILED = "FAILED"


class DemoState(StrEnum):
    """Finite state machine of a guided product demonstration."""

    IDLE = "IDLE"
    SOURCE_READY = "SOURCE_READY"
    ACQUIRING = "ACQUIRING"
    CONTEXT_READY = "CONTEXT_READY"
    DECODING = "DECODING"
    CONFIRMING = "CONFIRMING"
    INTENT_READY = "INTENT_READY"
    SAFETY_CHECK = "SAFETY_CHECK"
    AUTHORIZED = "AUTHORIZED"
    HIL_EXECUTING = "HIL_EXECUTING"
    COMPLETED = "COMPLETED"
    HELD = "HELD"
    DENIED = "DENIED"
    FAILED = "FAILED"
    RECOVERING = "RECOVERING"


class SystemHealthStatus(StrEnum):
    """Aggregated subsystem health indicator."""

    HEALTHY = "HEALTHY"
    READY = "READY"
    ACTIVE = "ACTIVE"
    DEGRADED = "DEGRADED"
    BLOCKED = "BLOCKED"
    STALE = "STALE"
    ERROR = "ERROR"


class ProductDemoScenario(StrEnum):
    """6 Golden Demonstration Scenarios."""

    PRODUCT_A = "PRODUCT_A"
    PRODUCT_B = "PRODUCT_B"
    PRODUCT_C = "PRODUCT_C"
    PRODUCT_D = "PRODUCT_D"
    PRODUCT_E = "PRODUCT_E"
    PRODUCT_F = "PRODUCT_F"


class ProductStage(StrEnum):
    """7 canonical architecture pipeline stages."""

    SENSORS = "SENSORS"
    SIGNAL = "SIGNAL"
    DECODING = "DECODING"
    CONFIDENCE = "CONFIDENCE"
    INTENT = "INTENT"
    SAFETY = "SAFETY"
    HIL = "HIL"
    RESEARCH = "RESEARCH"


class ProductExecutionOutcome(StrEnum):
    """Outcome of an end-to-end product execution."""

    PASS = "PASS"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"

